linters:
  disable-all: false
  enable:
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - govet
    - lll
    - misspell
    - nakedret
    - nolintlint
    - exportloopref
    - unconvert
    - whitespace
    # - typecheck

linters-settings:
  gocyclo:
    min-complexity: 25
  golint:
    min-confidence: 0
  lll:
    line-length: 250
  misspell:
    locale: US
  cyclop:
    max-complexity: 20
  funlen:
    lines: -1
    statements: 45
  nestif:
    min-complexity: 10
  dupl:
    threshold: 350

# issues:
#   exclude-rules:
#   - path: ../
#     linters:
#     - typecheck

run:
  timeout: 10m
  issues-exit-code: 3

  skip-dirs:
    - tests
    - tools
    - deploy

  skip-dirs-use-default: false
  modules-download-mode: readonly
  go: "1.20"
