run:
  timeout: 5m

linters:
  enable:
  - asciicheck
  - unused
  - depguard
  - errorlint
  - gofmt
  - gosec
  - goimports
  - importas
  - prealloc
  - revive
  - misspell
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - whitespace
