version: 2

project_name: vimp

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

gomod:
  proxy: false

builds:
  - id: vimp
    binary: vimp
    mod_timestamp: '{{ .CommitTimestamp }}'
    dir: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -w
      - -s
      - -extldflags "-static"
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

universal_binaries:
  - id: vimp
    name_template: 'vimp'
    replace: true

sboms:
  - artifacts: binary

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
  algorithm: sha256

snapshot:
  version_template: '{{ .Tag }}-next'

report_sizes: true

metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'

release:
  github:
    owner: mchmarny
    name: vimp
  prerelease: auto

archives:
  - id: vimp
    ids:
      - vimp
    formats:
      - binary
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^build:'
      - '^docs:'
      - '^test:'
      - '^lint:'
      - '^chore: readme'
      - '^chore: bump version'
      - typo
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?(fix|bug)(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Tasks
      regexp: '^.*?chore(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

brews:
  - ids:
      - vimp
    repository:
      owner: mchmarny
      name: homebrew-vimp
      token: '{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}'
    homepage: 'https://github.com/mchmarny/vimp'
    description: 'Vulnerability Import CLI'
    directory: Formula
    license: 'Apache-2.0'
    test: |
      system "#{bin}/vimp --version"

nfpms:
  - file_name_template: 'vimp-{{.Version}}_{{.Os}}-{{.Arch}}'
    homepage: https://github.com/mchmarny/vimp/
    description: 'Vulnerability Import CLI'
    maintainer: vimp developers <vimp@thingz.io>
    license: Apache 2.0
    vendor: vimp developers
    formats:
      - deb
      - rpm
    bindir: /usr/bin
