name: 'Verify Provenance'
description: 'Verifies SLSA provenance of release artifacts'

inputs:
  checksums:
    description: 'Base64-encoded checksums from release'
    required: true
  attestation_file:
    description: 'Name of the attestation file'
    required: false
    default: 'multiple.intoto.jsonl'

runs:
  using: 'composite'
  steps:
    - name: Install SLSA Verifier
      uses: slsa-framework/slsa-verifier/actions/installer@6657aada084353c65e5dde35394b1a010289fab0  # v2.7.0

    - name: Download Assets
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" -p "vimp*"
        gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" -p "${{ inputs.attestation_file }}"

    - name: Verify Assets
      shell: bash
      env:
        CHECKSUMS: ${{ inputs.checksums }}
      run: |
        set -euo pipefail
        checksums=$(echo "$CHECKSUMS" | base64 -d)
        while read -r line; do
            artifact=$(echo $line | cut -d ' ' -f2)
            slsa-verifier verify-artifact --provenance-path "${{ inputs.attestation_file }}" \
                                          --source-uri "github.com/$GITHUB_REPOSITORY" \
                                          --source-tag "$GITHUB_REF_NAME" \
                                          "$artifact"
        done <<<"$checksums"
