substitutions:
  _IMG_NAME: node-demo
  _IMG_VERSION: v0.0.2

steps:

  # Build image
  - id: build
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    dir: examples/cloud-build
    args:
    - -c
    - |
      docker build \
        -t "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_IMG_NAME}:${_IMG_VERSION}" \
        .

  # Publish image
  - id: publish
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    waitFor:
    - build
    dir: examples/cloud-build
    args:
    - -c
    - |-
      docker push "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_IMG_NAME}:${_IMG_VERSION}"
      docker image inspect "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_IMG_NAME}:${_IMG_VERSION}" \
        --format '{{index .RepoDigests 0}}' > image-digest.txt
      cat image-digest.txt

  - id: debug
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    waitFor:
    - publish
    dir: examples/cloud-build
    args:
    - -c
    - |-
      _TEST=$(cat image-digest.txt)
      echo $_TEST

  - id: scan
    waitFor:
    - publish
    name: anchore/grype
    dir: examples/cloud-build
    args:
    - -vv
    - --add-cpes-if-none
    - -s
    - AllLayers
    - -o
    - json
    - --file
    - report.json
    - "$(cat image-digest.txt)"

  # The Dockerfile used to generate this image is located in the vulctl repo.
  # https://github.com/mchmarny/vulctl/blob/main/Dockerfile
  - id: import
    waitFor:
    - scan
    name: us-west1-docker.pkg.dev/cloudy-build/vulctl/vulctl
    dir: examples/cloud-build
    args:
    - import
    - --project
    - $PROJECT_ID
    - --source
    - "$(cat image-digest.txt)"
    - --file
    - report.json
    - --format
    - grype

images:
- ${LOCATION}-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_IMG_NAME:${_IMG_VERSION}