substitutions:
  _IMG_NAME: node-demo

steps:

  # Build image
  - id: build
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    dir: app
    args:
    - -c
    - |
      docker build --build-arg VERSION=${TAG_NAME} \
        -t "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_IMG_NAME}:${COMMIT_SHA}" \
        -t "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_IMG_NAME}:${TAG_NAME}" \
        .
  
  # Publish image
  - id: publish
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    waitFor: 
    - build
    dir: app
    args:
    - -c
    - |-
      docker push "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_IMG_NAME}:${TAG_NAME}"
      docker image inspect "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_IMG_NAME}:${TAG_NAME}" \
        --format '{{index .RepoDigests 0}}' > image-digest.txt
      cat image-digest.txt

  - id: scan
    waitFor: 
    - publish
    name: anchore/grype
    args: ['--add-cpes-if-none', '-s', 'AllLayers', '-o', 'json', '--file', 'report.json', '$(cat image-digest.txt)']

  # The Dockerfile used to generate this image is located in the vulctl repo.
  # https://github.com/mchmarny/vulctl/blob/main/Dockerfile
  - id: import
    name: us-west1-docker.pkg.dev/cloudy-build/vulctl/vulctl
    waitFor:
    - scan
    args: ['import', '--project', '$PROJECT_ID', '--source', '$(cat image-digest.txt)', '--file', 'report.json', '--format', 'grype']

images:
- ${LOCATION}-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_IMG_NAME:$TAG_NAME