substitutions:
  _IMAGE_URI: us-west1-docker.pkg.dev/cloudy-build/vulctl/ruby-demo@sha256:666b0f0498092184d635ac8fc53e30586f7bb8895e7ed8afba60632398c1af74

steps:

  # - id: build
  # Build the container image and capture the image digest.
  # For purposes of this demo, this example is using a pre-built image.

  - id: scan
    name: anchore/grype
    args: ['--add-cpes-if-none', '-s', 'AllLayers', '-o', 'json', '--file', 'report.json', '${_IMAGE_URI}']

  # The Dockerfile used to generate this image is located in the vulctl repo.
  # https://github.com/mchmarny/vulctl/blob/main/Dockerfile
  - id: import
    name: us-west1-docker.pkg.dev/cloudy-build/vulctl/vulctl@sha256:b7a5357e60ec723159004d54d6973673d6a0125b0c5ebfa7005a82a3ad3116ce
    waitFor:
    - scan
    args: ['import', '--project', '$PROJECT_ID', '--source', '${_IMAGE_URI}', '--file', 'report.json', '--format', 'grype']


options:
  requestedVerifyOption: VERIFIED

tags:
- demo