#!/bin/bash

set -e

msg () {
   echo "====== running $1 tests ======"
}

msg "root"
bin/vulctl -v
bin/vulctl -h

msg "import"
bin/vulctl import -s snyk \
                  -f data/snyk.json \
                  -i us-docker.pkg.dev/project/repo/img@sha256:f6efe
