#!/bin/bash

set -e

msg () {
   echo "====== running $1 tests ======"
}

msg "root"
bin/vulctl -v
bin/vulctl -h

msg "import"
bin/vulctl import --source us-docker.pkg.dev/project/repo/img@sha256:f6efe \
                  --file data/snyk.json \
                  --format snyk

bin/vulctl import --source us-docker.pkg.dev/project/repo/img@sha256:f6efe \
                  --file data/grype.json \
                  --format grype
