#!/bin/bash

set -euo pipefail

digest=$1

# grype
grype -q --add-cpes-if-none -s AllLayers -o json --file examples/data/grype.json $digest

# trivy
trivy image --format json --output examples/data/trivy.json $digest

# snyk
snyk container test --app-vulns --json-file-output=examples/data/snyk.json $digest