#!/bin/bash

set -euo pipefail

digest="us-west1-docker.pkg.dev/cloudy-labz/cloudbuild-demo/hello@sha256:1ea4ce8b8cbc3c5c44a2edc059ebf91e6f9c067588386855df4c88fc0036d9fc"

bin/vulctl import --project cloudy-labz \
                  --source $digest \
                  --file data/snyk.json \
                  --format snyk


gcloud artifacts docker images describe $digest \
    --project cloudy-labz \
    --show-all-metadata \
    --format json | jq -r .