#!/bin/bash

set -euo pipefail

digest="us-west1-docker.pkg.dev/cloudy-labz/hello/hello@sha256:a30db8a25a48a19ff1e92ef3a56a3b4ce8b70955a7d6b6add7461c1ea54ce083"

bin/vulctl import --project cloudy-labz \
                  --source $digest \
                  --file data/snyk.json \
                  --format snyk


gcloud artifacts docker images describe $digest \
    --project cloudy-labz \
    --show-all-metadata \
    --format json | jq -r .