#!/bin/bash

set -euo pipefail

digest="us-west1-docker.pkg.dev/cloudy-labz/builders/sbominator@sha256:cdcd67d7e7b444eb38d67ee6078f6f01d98d3ad9252d94a99cfce7eee2107a87"

bin/vulctl import --project cloudy-labz \
                  --source $digest \
                  --file data/test.json \
                  --format snyk


gcloud artifacts docker images describe $digest \
    --project cloudy-labz \
    --show-all-metadata \
    --format json | jq -r .