#!/bin/bash

set -euo pipefail

digest=$1

# grype
grype -q --add-cpes-if-none -s AllLayers -o json --file tmp/grype.json $digest

# trivy
trivy image --format json --output tmp/trivy.json $digest

# snyk
snyk container test --app-vulns --json-file-output=tmp/snyk.json $digest