name: import-vulnerabilities

on:
  workflow_call:
    inputs:
      image_digest:
        description: 'Fully-qualified image uri (repo/image@digest)'
        required: true
        type: string
      auth_provider:
        description: 'OIDC provider ID'
        required: true
        type: string
      auth_user:
        description: 'OIDC user ID'
        required: true
        type: string
      target_project:
        description: 'Target project ID where vulnerability scan will be imported'
        required: true
        type: string
      report_path:
        description: 'Path to vulnerability scan report'
        type: string
        default: 'report.json'

permissions:
  contents: read

jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
    steps:

    - name: Checkout Code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0

    - id: auth
      name: Auth GCP
      uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d  # v1.0.0
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.auth_provider }}
        service_account: ${{ inputs.auth_user }}

    - id: scan
      name: Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image_digest }}
        scanners: vuln
        format: json
        output: ${{ inputs.report_path }}
        timeout: 5m
        hide-progress: true

    - uses: mchmarny/vulctl@main
      with:
        project: ${{ inputs.target_project }}
        digest: ${{ inputs.image_digest }}
        file: ${{ inputs.report_path }}
        format: trivy
