name: schedule

on:
  # schedule:
  #  - cron: '30 */8 * * *'
  workflow_dispatch:
    inputs:
      image:
        description: 'Debug'
        required: false
        default: 'false'

permissions:
  contents: read

jobs:
  queue-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
    - name: Spool Images
      env:
        GH_TOKEN: ${{ github.token }}
      run: |-
        while read img; do
          # skip comments
          if [[ $img =~ ^[[:space:]]*\#.*$ ]]; then
            continue
          fi
          echo "image: $img"
          gh workflow run .github/workflows/process.yaml -f image="$img"
        done < ./image.txt
