name: test
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    permissions:
      contents: read
      security-events: write
    with:
      go-version: ^1.20.5
      scan-severity: 'CRITICAL,HIGH,MEDIUM'
      golangci_version: v1.53.2
