name: push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    permissions:
      contents: read
    with:
      go-version: ^1.20.1
      scan-severity: 'CRITICAL,HIGH,MEDIUM'
