name: release-cli
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'  # Only build tag with semantic versioning format

permissions:
  contents: read

jobs:

  conf:
    env:
      GO_VERSION: ^1.20.5
      SYFT_VERSION: v0.14.1
      LINTER_VERSION: v1.53.2
      ERR_VULNERABILITY_SEV: "CRITICAL,HIGH,MEDIUM"

    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      go_version: ${{ steps.conf.outputs.go_version }}
      syft_version: ${{ steps.conf.outputs.syft_version }}
      err_on_vulnerability_sev: ${{ steps.conf.outputs.err_on_vulnerability_sev }}
      linter_version: ${{ steps.conf.outputs.linter_version }}
    steps:

    - name: Export Config
      id: conf
      run: |
        echo "go_version=${{ env.GO_VERSION }}" >> $GITHUB_OUTPUT
        echo "syft_version=${{ env.SYFT_VERSION }}" >> $GITHUB_OUTPUT
        echo "err_on_vulnerability_sev=${{ env.ERR_VULNERABILITY_SEV }}" >> $GITHUB_OUTPUT
        echo "linter_version=${{ env.LINTER_VERSION }}" >> $GITHUB_OUTPUT

  test:
    uses: ./.github/workflows/test.yaml
    permissions:
      contents: read
      security-events: write
    with:
      go-version: ${{ needs.conf.outputs.go_version }}
      scan-severity: ${{ needs.conf.outputs.err_on_vulnerability_sev }}
      golangci_version: ${{ needs.conf.outputs.linter_version }}

  release:
    outputs:
      hashes: ${{ steps.checksum.outputs.hashes }}
    runs-on: ubuntu-latest
    needs:
    - test
    permissions:
      contents: write
    steps:
    - name: Setup Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753  # v4.0.1
      with:
        go-version: ${{ needs.conf.outputs.go_version }}
    - run: go version
    - name: Cache Go Modules
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8  # v3.3.1
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Checkout Code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3
    - name: Prune Git History
      run: git fetch --prune --unshallow
    - name: Install Syft
      uses: anchore/sbom-action/download-syft@78fc58e266e87a38d4194b2137a3d4e9bcaf7ca1  # v0.14.3
      with:
        version: ${{ needs.conf.outputs.syft_version }}
    - name: Build CLI
      uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b  # v4.2.0
      id: releaser
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
    - name: Gen Hashes
      id: checksum
      env:
        ARTIFACTS: "${{ steps.releaser.outputs.artifacts }}"
      run: |
        set -euo pipefail
        checksum_file=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Checksum") | .path')
        echo "hashes=$(cat $checksum_file | base64 -w0)" >> $GITHUB_OUTPUT

  provenance:
    needs:
    - release
    permissions:
      actions: read    # To read the workflow path.
      id-token: write  # To sign the provenance.
      contents: write  # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.7.0
    with:
      base64-subjects: "${{ needs.release.outputs.hashes }}"
      upload-assets: true
      compile-generator: true

  verify:
    env:
      ATT_FILE_NAME: "multiple.intoto.jsonl"
    needs:
    - release
    - provenance
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Install SLSA Verifier
        uses: slsa-framework/slsa-verifier/actions/installer@c9abffe4d2ab2ffa0b2ea9b2582b84164f390adc  # v2.3.0
      - name: Download Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" -p "vimp*"
          gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" -p "$ATT_FILE_NAME"
      - name: Verify Assets
        env:
          CHECKSUMS: ${{ needs.release.outputs.hashes }}
        run: |
          set -euo pipefail
          checksums=$(echo "$CHECKSUMS" | base64 -d)
          while read -r line; do
              artifact=$(echo $line | cut -d ' ' -f2)
              slsa-verifier verify-artifact --provenance-path "$ATT_FILE_NAME" \
                                            --source-uri "github.com/$GITHUB_REPOSITORY" \
                                            --source-tag "$GITHUB_REF_NAME" \
                                            "$artifact"
          done <<<"$checksums"
