name: On-Tag Release Image
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:

  conf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      go_version: ${{ steps.versions.outputs.go }}
      golangci_lint_version: ${{ steps.versions.outputs.golangci_lint }}
      cosign_version: ${{ steps.versions.outputs.cosign }}
      image_name: ${{ steps.conf.outputs.image_name }}
      provider_id: ${{ steps.conf.outputs.provider_id }}
      registry_uri: ${{ steps.conf.outputs.registry_uri }}
      service_account: ${{ steps.conf.outputs.service_account }}
      project_id: ${{ steps.conf.outputs.project_id }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Load versions
        id: versions
        uses: ./.github/actions/load-versions

      - name: Export Config
        id: conf
        run: |
          echo "image_name=vimp" >> $GITHUB_OUTPUT
          echo "provider_id=projects/595203407878/locations/global/workloadIdentityPools/vimp-github-pool/providers/github-provider" >> $GITHUB_OUTPUT
          echo "registry_uri=us-docker.pkg.dev/s3cme1/builders" >> $GITHUB_OUTPUT
          echo "service_account=vimp-github-actions-user@s3cme1.iam.gserviceaccount.com" >> $GITHUB_OUTPUT
          echo "project_id=s3cme1" >> $GITHUB_OUTPUT

  test:
    needs:
    - conf
    uses: ./.github/workflows/test.yaml
    permissions:
      contents: read
      security-events: write

  image:
    needs:
    - conf
    - test
    permissions:
      contents: read
      actions: read
      id-token: write
      packages: write
    uses: ./.github/workflows/build.yaml
    with:
      auth_provider: ${{ needs.conf.outputs.provider_id }}
      auth_user: ${{ needs.conf.outputs.service_account }}
      image_name: ${{ needs.conf.outputs.image_name }}
      image_repo: ${{ needs.conf.outputs.registry_uri }}
      go_version: ${{ needs.conf.outputs.go_version }}

  sign:
    needs:
    - conf
    - image
    permissions:
      contents: read
      actions: read
      id-token: write
    uses: ./.github/workflows/sign.yaml
    with:
      auth_provider: ${{ needs.conf.outputs.provider_id }}
      auth_user: ${{ needs.conf.outputs.service_account }}
      cosign_version: ${{ needs.conf.outputs.cosign_version }}
      image_digest: ${{ needs.image.outputs.digest }}

  provenance:
    needs:
    - conf
    - sign
    - image
    permissions:
      contents: read
      actions: read
      id-token: write
      packages: write
    uses: ./.github/workflows/slsa.yaml
    with:
      auth_provider: ${{ needs.conf.outputs.provider_id }}
      auth_user: ${{ needs.conf.outputs.service_account }}
      cosign_version: ${{ needs.conf.outputs.cosign_version }}
      image_digest: ${{ needs.image.outputs.digest }}
