name: tag
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'  # Only build tag with semantic versioning format

permissions:
  contents: read

jobs:

  test:
    uses: ./.github/workflows/test.yaml
    permissions:
      contents: read
    with:
      go-version: ^1.20.1
      scan-severity: 'CRITICAL,HIGH,MEDIUM'

  release-cli:
    runs-on: ubuntu-latest
    needs:
    - test
    permissions:
      contents: write
    steps:
    - name: Setup Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568  # v3.5.0
      with:
        go-version: ^1.20.1
    - run: go version
    - name: Cache Go Modules
      uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0  # v3.2.6
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Checkout Code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
      with:
        fetch-depth: 2
    - name: Install Syft
      uses: anchore/sbom-action/download-syft@07978da4bdb4faa726e52dfc6b1bed63d4b56479  # v0.13.3
      with:
        version: v0.13.1
    - name: Build CLI
      uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b  # v4.2.0
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
