name: process

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to process'
        required: true

jobs:

  process-grype:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

    - name: Install grype
      uses: anchore/scan-action/download-grype@869c549e657a088dc0441b08ce4fc0ecdac2bb65  # v5.3.0

    - name: Scan grype
      run: |-
        grype -q \
          --add-cpes-if-none \
          -s AllLayers \
          -o json \
          --file ./report.json \
          ${{ inputs.image }} || true

    - name: Print grype
      run: |
        echo "grype: ./report.json"
        cat ./report.json

  process-trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

    - name: Scan trivy
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8  # 0.33.1
      with:
        image-ref: ${{ inputs.image }}
        scan-type: image
        format: json
        output: ./results.json
        hide-progress: true
        scanners: vuln

    - name: Print trivy
      run: |
        echo "trivy: ./results.json"
        cat ./results.json

  process-snyk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

    - name: Scan snyk
      uses: snyk/actions/docker@de2dda699bf7276d103ed6a72a5bc5a1871ad658  # v0.5.0
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
      with:
        image: ${{ inputs.image }}
        args: --json-file-output=./results.json

    - name: Print snyk
      run: |
        echo "snyk: ./results.json"
        cat ./results.json
