name: process

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to process'
        required: true

jobs:

  process-gryp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

    - name: Install grype
      uses: anchore/scan-action/download-grype@4be3c24559b430723e51858969965e163b196957  # v3.3.5

    - name: Scan grype
      run: |-
        grype -q \
          --add-cpes-if-none \
          -s AllLayers \
          -o json \
          --file ./report.json \
          ${{ inputs.image }} || true

    - name: Print grype
      run: |
        echo "grype: ./report.json"
        cat ./report.json

  process-trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

    - name: Scan trivy
      uses: aquasecurity/trivy-action@b43daad0c3c96202fc5800b511dfae8e6ecce864  # v0.11.0
      with:
        image-ref: ${{ inputs.image }}
        scan-type: image
        format: json
        output: ./results.json
        hide-progress: true
        scanners: vuln

    - name: Print trivy
      run: |
        echo "trivy: ./results.json"
        cat ./results.json

  process-snyk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

    - name: Scan snyk
      uses: snyk/actions/docker@7fad562681122205233d1242c3bb39598c5393da  # v0.3.0
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
      with:
        image: ${{ inputs.image }}
        args: --json-file-output=./results.json

    - name: Print snyk
      run: |
        echo "snyk: ./results.json"
        cat ./results.json
