name: sign-image

on:
  workflow_call:
    inputs:
      image_digest:
        description: 'Fully-qualified image digest to verify (registry/image@sha256:digest)'
        required: true
        type: string
      auth_provider:
        description: 'OIDC provider ID'
        required: true
        type: string
      auth_user:
        description: 'OIDC user ID'
        required: true
        type: string
      cosign_version:
        description: 'The version of cosign to use'
        required: false
        type: string
        default: 'v1.13.1'
      scan_severity:
        description: 'Error on vulnerability scan severity'
        required: false
        type: string
        default: 'CRITICAL,HIGH,MEDIUM'

permissions:
  contents: read

jobs:

  sign:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
    steps:

    - id: auth
      name: Auth GCP
      uses: google-github-actions/auth@e8df18b60c5dd38ba618c121b779307266153fbf  # v1.1.0
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.auth_provider }}
        service_account: ${{ inputs.auth_user }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@204a51a57a74d190b284a0ce69b44bc37201f343  # v3.0.3
      with:
        cosign-release: ${{ inputs.cosign_version }}

    - name: Auth Cosign
      run: |
        set -euo pipefail
        cosign version
        reg=$(echo ${{ inputs.image_digest }} | cut -d/ -f1)
        cosign login ${reg} --username=oauth2accesstoken --password=${{ steps.auth.outputs.access_token }}

    - name: Generate Keys
      run: |
        set -euo pipefail
        COSIGN_PASSWORD=$(openssl rand -base64 12)
        cosign generate-key-pair

    - name: Attest Image
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        set -euo pipefail
        cosign sign ${{ inputs.image_digest }} \
            --force \
            --key cosign.key \
            -a sha=${{ github.sha }} \
            -a run_id=${{ github.run_id }} \
            -a run_attempt=${{ github.run_attempt }} \
            -a tag=${{ env.GITHUB_REF_NAME }}

    - name: Attest Image
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        set -euo pipefail
          cosign verify \
          --key cosign.pub \
          ${{ inputs.image_digest }}
